### ISSUE TITLE
fbx visualization

### ISSUE THREAD

**Issue by xiaozhuge080** [InterDigitalInc/UnderPressure#1]
Thanks for sharing the wonderful work!

I'm having some problems visualizing an fbx file in maya2022, it doesn't look like a human skeleton. 

![image](https://user-images.githubusercontent.com/10765920/184272951-54efd613-0244-47c9-90c7-de239b954906.png)

**Comment by mourotlucas** [comment]
Thanks for your positive feedback!

I tried to open an fbx file with fbx review and 3ds max (screenshots below), and it seems that the problem doesn't come from the data itself. I'm not very familiar with maya so I don't know how I can help you, sorry

fbx review:
![fbx review](https://user-images.githubusercontent.com/107840307/191294576-e075db12-4af1-4d68-947a-5e125439f60f.png)

3ds max:
![3ds max](https://user-images.githubusercontent.com/107840307/191294586-72a84f72-d0aa-4bab-a528-725368ae1985.png)

**Comment by xiaozhuge080** [comment]
Thank you very much! I will check further.
