### ISSUE TITLE
how to use on bvh file

### ISSUE THREAD

**Issue by kotaxyz** [InterDigitalInc/UnderPressure#10]
hello there , thanks dev for this awesome project ,i just want to know how to use the pretrained data provided , i have a bvh file for example how to clean the foot contacts in it and export it back

**Comment by Dong09** [comment]
are you sucessful ?

**Comment by Dong09** [comment]
Did you succeed？

**Comment by kotaxyz** [comment]
> Did you succeed？

i gave up on it
