### ISSUE TITLE
  Joint orientation

### ISSUE THREAD

**Issue by theoldgun** [InterDigitalInc/UnderPressure#4]
Thank you for your paper, which is very valuable!

I want to test the data captured by my own xsens with your training model, but I encounter several problems:

1. How is the skeleton coordinate system stored in the mvnx file defined? I only know that the z axis is upward.

2. Are the angles stored in the mvnx piece relative to the quaternion of the parent joint or the quaternion of the world? How do they arrange their xyz order?

We look forward to your reply!

**Comment by mourotlucas** [comment]
If I remember well, mvnx files store data in XYZ order for both skeleton and joint orientations, and joint orientations are expressed with respect to the global frame.

You will find all details about .mvnx files in MVN User Manual: https://www.xsens.com/hubfs/MVN_User_Manual.pdf?hsCtaTracking=1eacb2ea-b005-43d0-a2b7-55dbf7f6a4f7%7Cb08403d4-214e-42c7-9920-18ab2f35e714

You can also checkout out method 'parse' from class 'MVNX' in file 'parsing.py' which extract data from .mvnx files and method 'FK' in file 'anim.py' which computes global joint positions through forward kinematics from data extracted from .mvnx files.
