### ISSUE TITLE
Hello! Can you provide a file to detect the contact of the amass dataset?

### ISSUE THREAD

**Issue by JiahongWu1995** [InterDigitalInc/UnderPressure#5]
Hello! Can you provide a file to detect the contact of the amass dataset?thank you.

**Comment by mourotlucas** [comment]
Hello, unfortunately this is not possible due to AMASS licence terms which prohibit redistribution. You will have to download yourself AMASS dataset (after reading carefully licence terms and conditions since downloading means you acknowledge, understand them, and agree to be bound by them.)
