### ISSUE TITLE
smpl help in my video

### ISSUE THREAD

**Issue by luoww1992** [InterDigitalInc/UnderPressure#6]
i have a video, and get 24 smpl 3Dpoints by https://github.com/isarandi/metrabs/blob/master/docs/API.md .
video:

https://user-images.githubusercontent.com/45957595/209514207-1a0d07e8-0d36-4c1e-954a-166adcb53822.mp4

 24 smpl 3Dpoints:
the basic is millimeters 
[dr8.zip](https://github.com/InterDigitalInc/UnderPressure/files/10302052/dr8.zip)

show points:

https://user-images.githubusercontent.com/45957595/209514592-d950f601-5acb-48e5-acec-86f5c82db1e9.mp4

Then  run with https://github.com/InterDigitalInc/UnderPressure/issues/3#issuecomment-1363710544

but  i can not find the result show in func cleanup.
so something  is wrong, for help !

**Comment by luoww1992** [comment]
can you support a demo video like the default dataset  to run it ?

**Comment by mourotlucas** [comment]
Please note that our deep network has be trained on global 3D joint positions expressed in meters, i.e. as stored in .mvnx files (preprocessed data files), your problem might come from here.

Method 'footskate_cleanup' from 'demo.py' load sample from the given sample index which refers to the folder 'footskate_samples' containing motion sequences suffering from footskate artifacts. You must implement adapt this method to run footskate cleanup from other motion sequences.
